### ISSUE TITLE
Character Creation Failure

### ISSUE THREAD

**Issue by badbaki** [NexusForever/NexusForever#128]
_Aaaw Shoot..._
Character creation failure. Unsure of what exactly is causing it but here is a creation code that fails: `eNrj/cDAwMTAwMDCAAHLgZgdiEWBmBGIORkg8iAxZiBmg6qFiXFBMUhMEojdoPqKWEEqGBuYwSQLmGQFkpmLQSbM5QXpldkKMr34KEj//LO8QPL3OT4g+b+eH0wKAMlzbIJgthDIhAPCYLYIkOzgFAWzxYDks1PiYLYEkHTwAQCrURm4`

Here is the error:
```
13:14:42.8952[ERROR][Session] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NexusForever.WorldServer.Network.Message.Handler.CharacterHandler.<HandleCharacterCreate>g__GetCharacterCustomisation|2_0(Dictionary`2 customisations, UInt32 race, UInt32 sex, UInt32 primaryLabel, UInt32 primaryValue) in C:\Users\Baki\Desktop\NF-DevFork\NexusForever\Source\NexusForever.WorldServer\Network\Message\Handler\CharacterHandler.cs:line 310
   at NexusForever.WorldServer.Network.Message.Handler.CharacterHandler.HandleCharacterCreate(WorldSession session, ClientCharacterCreate characterCreate) in C:\Users\Baki\Desktop\NF-DevFork\NexusForever\Source\NexusForever.WorldServer\Network\Message\Handler\CharacterHandler.cs:line 211
   at NexusForever.Shared.Network.GameSession.HandlePacket(ClientGamePacket packet) in C:\Users\Baki\Desktop\NF-DevFork\NexusForever\Source\NexusForever.Shared\Network\GameSession.cs:line 186 System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NexusForever.WorldServer.Network.Message.Handler.CharacterHandler.<HandleCharacterCreate>g__GetCharacterCustomisation|2_0(Dictionary`2 customisations, UInt32 race, UInt32 sex, UInt32 primaryLabel, UInt32 primaryValue) in C:\Users\Baki\Desktop\NF-DevFork\NexusForever\Source\NexusForever.WorldServer\Network\Message\Handler\CharacterHandler.cs:line 310
   at NexusForever.WorldServer.Network.Message.Handler.CharacterHandler.HandleCharacterCreate(WorldSession session, ClientCharacterCreate characterCreate) in C:\Users\Baki\Desktop\NF-DevFork\NexusForever\Source\NexusForever.WorldServer\Network\Message\Handler\CharacterHandler.cs:line 211
   at NexusForever.Shared.Network.GameSession.HandlePacket(ClientGamePacket packet) in C:\Users\Baki\Desktop\NF-DevFork\NexusForever\Source\NexusForever.Shared\Network\GameSession.cs:line 186
```

**Comment by VoidEssy** [comment]
Want to try these. Some of them are variation of the same one maybe can narrow down which area is problematic I see very clear repeating pattern so we can maybe isolate the issue.
-------------------------------AURIN-------F------------------------
eNrj/cDAwMTAwMACxIxAvByIOYCYHcoHicPkmYGYC8pmharhhoqB2AJAzAPEkkAsAlXP2ABS/e0uSL7dkxcsAlL3v14YSCo+kwCLAACK9AlJ

eNrj/cDAwMTAwMACxIxAvByIOYCYHcoHicPkmYGYC8pmharhhoqB2AJAzAPEkkDsBlXP2ABS/e0uSL7dkxcsAlL3v14YSCo+kwCLAACT8Al7

eNrj/cDAwMTAwMACxIxAvByIOYCYHcoHicPkmYGYC8pmharhhoqB2AJAzAPEklC9IPWMDSDV3+6C5Ns9ecEiIHX/64WBpOIzCbAIAIeKCTY=

eNrj/cDAwMTAwMACxIxAvByIOYCYHcoHicPkmYGYC8pmharhhoqB2AJAzAPEkkAsAlXP2ABS/e0uSL7dkxcsAlL3v14YSCo+kwCLAACK9AlJ
--------------------DIFF RACES---Mordesh F-----------------------
eNrj/cDAwMTAwCAAxIxAvByI2YGYF8rnZIDIcwMxM5RmgWKQOlYgFoTSkkAsAtX3rx6ky7kHpIexgQVMgtSsSQDpsr3NCRYB2ZLxmB9IfrsLMqXXShgsDjJFhEUUSP6vBwAY+g6/

eNrj/cDAwMTAwCAAxIxAvByI2YGYD8rnZIDIcwMxM5RmgWKQOlYgFoTSkkAsAtX3vx6ky7kHpIexgQVMgtSsTQDpsr3NCRbhBZIZj0F2MTDwA/G3uyCzeq2EwbIgs0RZRMGmAQBWPg7R

**Comment by kirmmin** [comment]
@Serbaki , was this happening when in a certain mode or did both Novice & Veteran creation display the same issue?

**Comment by badbaki** [comment]
Both cause the error.
