### ISSUE TITLE
Equipping Items with multiple ItemDisplaySourceEntry entries fails

### ISSUE THREAD

**Issue by kirmmin** [NexusForever/NexusForever#133]
```
[FATAL][Inventory] System.NotImplementedException: The method or operation is not implemented.
   at NexusForever.WorldServer.Game.Entity.Item.GetDisplayId(Item2Entry entry) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Item.cs:line 35
   at NexusForever.WorldServer.Game.Entity.Inventory.GetItemVisual(ItemSlot itemSlot, Costume costume) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Inventory.cs:line 142
   at NexusForever.WorldServer.Game.Entity.Inventory.VisualUpdate(ItemSlot slot, Costume costume) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Inventory.cs:line 198
   at NexusForever.WorldServer.Game.Entity.Inventory.VisualUpdate(Item item) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Inventory.cs:line 185
   at NexusForever.WorldServer.Game.Entity.Inventory.ItemMove(ItemLocation from, ItemLocation to) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Inventory.cs:line 406 System.NotImplementedException: The method or operation is not implemented.
   at NexusForever.WorldServer.Game.Entity.Item.GetDisplayId(Item2Entry entry) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Item.cs:line 35
   at NexusForever.WorldServer.Game.Entity.Inventory.GetItemVisual(ItemSlot itemSlot, Costume costume) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Inventory.cs:line 142
   at NexusForever.WorldServer.Game.Entity.Inventory.VisualUpdate(ItemSlot slot, Costume costume) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Inventory.cs:line 198
   at NexusForever.WorldServer.Game.Entity.Inventory.VisualUpdate(Item item) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Inventory.cs:line 185
   at NexusForever.WorldServer.Game.Entity.Inventory.ItemMove(ItemLocation from, ItemLocation to) in C:\Users\Admin\Documents\NexusForever\Source\NexusForever.WorldServer\Game\Entity\Inventory.cs:line 406
```

The above error occurs when trying to equip http://www.jabbithole.com/items/frozen-wrangler-mitts-28366 - this item has multiple entries returned from the `ItemDisplaySourceEntry` GameTable. The way they seem to match when there's multiple entries seems to be a relation between `Item2.PowerLevel` and `ItemDisplaySourceEntry.ItemMaxLevel`. (Doing some testing and coding out a fix at the moment)

Thanks to Zentoth for replicating this bug.

**Comment by kirmmin** [comment]
Digging further into this, it appears that using the matching ItemDisplaySourceEntry (based on `Item2.PowerLevel` matching `ItemDisplaySourceEntry.ItemMaxLevel` when there's multiple matching `ItemDisplaySourceEntry`) resulted in a different visual than the preview window. It did stop the bugging of the character, though :)

I've solved the bug for this item on a branch that I'll push momentarily that falls back to using the DisplayId if there are multiple entries AND a `Item2.ItemDisplayId`, or uses the matching `ItemDisplaySourceEntry` which may look different than the preview. @Rawaho , it'd be good to understand why this if statement was put in: https://github.com/NexusForever/NexusForever/blob/develop/Source/NexusForever.WorldServer/Game/Entity/Item.cs#L27-L28.
